Control commit

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,7 @@
 #!/bin/bash
 
+hash ruby 2>&- || { echo >&2 "Fatal error: Package \"ruby\" is not installed on your system. Aborting..."; exit 1; }
+hash qmake 2>&- || { echo >&2 "Fatal error: Package \"qmake\" is not installed on your system. Aborting..."; exit 1; }
+
 export RUBYLIB=.:${RUBYLIB}
 ruby configure.rb $*
